name: aksw.org Assets Update

on:
  push:
    branches: [ main ]
  workflow_dispatch:
  schedule:
    - cron:  '45 * * * *'

env:
  BRANCH: main
  OAUTH_CLIENT_ID: ${{ secrets.CMEM_OAUTH_CLIENT_ID }}
  OAUTH_CLIENT_SECRET: ${{ secrets.CMEM_OAUTH_CLIENT_SECRET }}
  CMEMC_ENV_OVERWRITE: "True"

jobs:
  pipeline:
    runs-on: ubuntu-latest
    steps:
    - uses: arduino/setup-task@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
    - uses: actions/checkout@v3
      with:
        ref: ${{ env.BRANCH }}
    - name: Install Prerequisites
      run: |
        RELEASE=$(lsb_release -rs)
        echo "deb http://download.opensuse.org/repositories/home:/ailin_nemui:/Ubuntu:/curl/xUbuntu_$RELEASE/ /" | sudo tee /etc/apt/sources.list.d/home:ailin_nemui:Ubuntu:curl.list
        curl -fsSL https://download.opensuse.org/repositories/home:ailin_nemui:Ubuntu:curl/xUbuntu_$RELEASE/Release.key | gpg --dearmor | sudo tee /etc/apt/trusted.gpg.d/home_ailin_nemui_Ubuntu_curl.gpg > /dev/null
        sudo apt -q update
        sudo apt -q install curl libcurl4
        sudo apt-get -y install jq
        curl --version
    - name: "⚙️ Run CI Tasks"
      id: ci_step
      run: task ci
